dpaw-alerts/Models/SocialNetwork.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace dpaw_alerts.Models
{
    public class SocialNetwork
    {
        [Key]
        public int Id { get; set; }

        public string Channel { get; set; }

        [Display(Name ="App ID"),Required]
        public string AppId { get; set; }

        [Display(Name = "App Secret"), Required]
        public string AppSecret { get; set; }

        [Display(Name = "Access Token"), Required, DataType(DataType.MultilineText)]
        public string AccessToken { get; set; }

        [Display(Name = " Long Life Access Token"), DataType(DataType.MultilineText)]
        public string LongLifeAccessToken { get; set; }

        [Display (Name ="Token Expiry")]
        public DateTime? ExpiryDate { get; set; }

    }
}

dpaw-alerts/Controllers/SocialNetworksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using dpaw_alerts.Models;
using System.Net.Http;
using dpaw_alerts.Services;
using Facebook;
using System.Dynamic;
using System.Text;
using System.Security.Cryptography;
using System.IO;
using dpaw_alerts.ViewModels;

namespace dpaw_alerts.Controllers
{
    [CustomAuthorize(Roles ="Admin")]
    public class SocialNetworksController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: SocialNetworks
        public async Task<ActionResult> Index()
        {
            return View(await db.SocialNetworks.ToListAsync());
        }

        // GET: SocialNetworks/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SocialNetwork socialNetwork = await db.SocialNetworks.FindAsync(id);
            if (socialNetwork == null)
            {
                return HttpNotFound();
            }
            return View(socialNetwork);
        }

        // GET: SocialNetworks/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SocialNetworks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Channel,AppId,AppSecret,AccessToken,LongLifeAccessToken,ExpiryDate")] SocialNetwork socialNetwork)
        {
            if (ModelState.IsValid)
            {
                db.SocialNetworks.Add(socialNetwork);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(socialNetwork);
        }

        // GET: SocialNetworks/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SocialNetwork socialNetwork = await db.SocialNetworks.FindAsync(id);
            if (socialNetwork == null)
            {
                return HttpNotFound();
            }
            return View(socialNetwork);
        }

        // POST: SocialNetworks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Channel,AppId,AppSecret,AccessToken,LongLifeAccessToken,ExpiryDate")] SocialNetwork socialNetwork)
        {
            if (ModelState.IsValid)
            {
                db.Entry(socialNetwork).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(socialNetwork);
        }

        // GET: SocialNetworks/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SocialNetwork socialNetwork = await db.SocialNetworks.FindAsync(id);
            if (socialNetwork == null)
            {
                return HttpNotFound();
            }
            return View(socialNetwork);
        }

        // [HttpPost]
        public ActionResult FacebookAuth(string code)
        {
            // https://graph.facebook.com/v2.8/145798112110995?145798112110995?fields=access_token
            
            string page_id = "145798112110995";
            string app_id = "243610232718169";
            string app_secret = "1eec1b1924ea5ad043b8cfda69b8f69b";
            string scope = "publish_pages,manage_pages,publish_actions,user_events";
            string access_token = "";

            //if (Request["code"] == null)
            if (code == null)
            {
                Response.Redirect(string.Format(
                    "https://graph.facebook.com/oauth/authorize?client_id={0}&redirect_uri={1}&scope={2}",
                    app_id, Request.Url.AbsoluteUri, scope));

                //https://graph.facebook.com/oauth/access_token?grant_type=fb_exchange_token&client_id={0}&client_secret={1}&fb_exchange_token={3}
            }
            else
            {
                Dictionary<string, string> tokens = new Dictionary<string, string>();

                string url = string.Format("https://graph.facebook.com/oauth/access_token?client_id={0}&redirect_uri={1}&scope={2}&code={3}&client_secret={4}",
                    app_id, Request.Url.AbsoluteUri, scope, Request["code"].ToString(), app_secret);
                
                HttpWebRequest request = WebRequest.Create(url) as HttpWebRequest;

                using (HttpWebResponse response = request.GetResponse() as HttpWebResponse)
                {
                    StreamReader reader = new StreamReader(response.GetResponseStream());

                    string vals = reader.ReadToEnd();

                    foreach (string token in vals.Split('&'))
                    {
                        //meh.aspx?token1=steve&token2=jake&...
                        tokens.Add(token.Substring(0, token.IndexOf("=")),
                            token.Substring(token.IndexOf("=") + 1, token.Length - token.IndexOf("=") - 1));
                    }
                }


                // string access_token =  "EAAC7gaECrVsBAMHcKZARZCH0BuJ3j4Wm71TDnEgWO7fAywXcs2jt88ZAktc1bZAprh7FkMH1abpEZBTFfKQRKRGo7BxXl26wifTM0ZAdVqmVUloKXDlTYQpmWWcSXZAv6EB4pgT4AypRRUBIpAZCre73IMUMa8sZCTp7HgrUnFh5uJgZDZD";
                //"EAACEdEose0cBAFt1OSr3fj9irUZBnp1nKYVeL4koXxKSl13ZBz3Uo8aUcTrTdRtbbgRV1rFAe0TT4YU58q5xESqioXN1ZA3RB6x45ZBpiL675sgC2kPZC0KcbxPgoXdlxkzfROx1fg1TCgdK0tZAoRLxZCzjyGav90f7krJCCmXFAZDZD"

                access_token = tokens["access_token"];

                var client = new FacebookClient(access_token);

                // client.Post("/me/feed", new { message = "markhagan.me video tutorial" });
                dynamic parameters = new ExpandoObject();
                // parameters.title = "App title";
                parameters.access_token = access_token;
                parameters.message = "Posted from my mvc application";
                // parameters.link = "http://www.natiska.com/article.html";
                // parameters.picture = "http://www.natiska.com/dav.png";
                //parameters.name = "Article Title";
                //  parameters.caption = "Caption for the link";
                parameters.appsecret_proof = FaceBookSecret(access_token, app_secret);

              //  var result = client.Post("/" + page_id + "/feed", parameters);


            }

            TempData["fbmsg"] =string.Format( "You have successfully authorised the DPaW App to post in Facebook on your behalf. Access token - {0}",access_token);
            // return Content("Facebook post success, Token - {0}", code);
            return RedirectToAction("Index");
        }

        internal static string FaceBookSecret(string content, string key)
        {
            byte[] keyBytes = Encoding.UTF8.GetBytes(key);
            byte[] messageBytes = Encoding.UTF8.GetBytes(content);
            byte[] hash;
            using (HMACSHA256 hmacsha256 = new HMACSHA256(keyBytes))
            {
                hash = hmacsha256.ComputeHash(messageBytes);
            }

            StringBuilder sbHash = new StringBuilder();
            for (int i = 0; i < hash.Length; i++)
            {
                sbHash.Append(hash[i].ToString("x2"));
            }
            return sbHash.ToString();
        }

        public ActionResult Tweet()
        {
            var sendTweetVM = new SendTweetViewModel
            {
                Message = "Testing async LINQ to Twitter in MVC - " + DateTime.Now.ToString()
            };

            return View(sendTweetVM);
        }

        [HttpPost]
        [ActionName("Tweet")]
        public async Task<ActionResult> TweetAsync(SendTweetViewModel tweet)
        {

            //var credentials = auth.CredentialStore;
            //string oauthToken = credentials.OAuthToken;
            //string oauthTokenSecret = credentials.OAuthTokenSecret;
            //string screenName = credentials.ScreenName;
            //ulong userID = credentials.UserID;

            //var auth = new MvcAuthorizer
            //{
            //    CredentialStore = new SessionStateCredentialStore()
            //    {
            //        ConsumerKey = ConsumerKey,
            //        ConsumerSecret = AppSecret,
            //        OAuthToken = AccessToken,
            //        OAuthTokenSecret= TokenSecret

            //    }
            //};

            //var ctx = new TwitterContext(auth);

            //Status responseTweet = await ctx.TweetAsync(tweet.Message);

            ////var responseTweetVM = new SendTweetViewModel();
            //tweet.Message = "Testing async LINQ to Twitter in MVC - " + DateTime.Now.ToString();
            //tweet.Response = "Tweet successful! Response from Twitter: " + responseTweet.Text;

            //ViewBag.Message= "Tweet successful! Response from Twitter: " + responseTweet.Text;

            return View(tweet);
        }

        [HttpPost]
        public ActionResult getToken(string appId, string appSecret, string accessToken)
        {

            var tokenUri = new Uri(
                   string.Format(

dpaw-alerts/Views/SocialNetworks/Create.cshtml
@model dpaw_alerts.Models.SocialNetwork

@{
    ViewBag.Title = "Create";
}

<div id="breadcrumb">
    <ul class="breadcrumb">
        <li><i class="fa fa-home"></i><a href="~/Home"> Home</a></li>

        <li class="active">Social Network API</li>
    </ul>
</div><!-- /breadcrumb-->
<div class="main-header clearfix">
    <div class="page-title">
        <h3 class="no-margin">Social Network API</h3>
        <span>Social Network API integration</span>
    </div><!-- /page-title -->

</div><!-- /main-header -->


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="row padding-md">
        <div class="col-md-6">


            <div class="form-horizontal">
                
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Channel, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Channel, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Channel, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.AppId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.AppId, new { htmlAttributes = new { @class = "form-control" } }) Twitter: Consumer Key
                        @Html.ValidationMessageFor(model => model.AppId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.AppSecret, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.AppSecret, new { htmlAttributes = new { @class = "form-control" } })
                        Twitter: Consumer Secret
                        @Html.ValidationMessageFor(model => model.AppSecret, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.AccessToken, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.AccessToken, new { htmlAttributes = new { @class = "form-control" } })
                        Twitter: Access Token
                        @Html.ValidationMessageFor(model => model.AccessToken, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.LongLifeAccessToken, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.LongLifeAccessToken, new { htmlAttributes = new { @class = "form-control" } })
                        Twitter: Token Secret
                        @Html.ValidationMessageFor(model => model.LongLifeAccessToken, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ExpiryDate, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ExpiryDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ExpiryDate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })  <input type="submit" value="Create" class="btn btn-info" />
                    </div>
                </div>
            </div>

        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

dpaw-alerts/Views/SocialNetworks/Delete.cshtml
@model dpaw_alerts.Models.SocialNetwork

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SocialNetwork</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Channel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Channel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AppId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AppId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AppSecret)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AppSecret)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccessToken)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccessToken)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LongLifeAccessToken)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LongLifeAccessToken)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExpiryDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExpiryDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

dpaw-alerts/Views/SocialNetworks/Details.cshtml
@model dpaw_alerts.Models.SocialNetwork

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>SocialNetwork</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Channel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Channel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AppId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AppId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AppSecret)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AppSecret)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccessToken)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccessToken)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LongLifeAccessToken)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LongLifeAccessToken)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExpiryDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExpiryDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

dpaw-alerts/Views/SocialNetworks/Edit.cshtml
@model dpaw_alerts.Models.SocialNetwork

@{
    ViewBag.Title = "Edit";
}
<div id="breadcrumb">
    <ul class="breadcrumb">
        <li><i class="fa fa-home"></i><a href="~/Home/"> Home</a></li>
        <li><a href="~/SocialNetworks/"> API Integration</a></li>
        <li class="active">Edit integration</li>
    </ul>
</div><!-- /breadcrumb-->
<div class="main-header clearfix">
    <div class="page-title">
        <h3 class="no-margin">Systems Integration</h3>
        <span>Please be cautious when updating any API parameter.</span>
    </div><!-- /page-title -->


</div><!-- /main-header -->

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
       
        @if (Model.Channel == "Facebook")
        {
            <div class="alert alert-warning">

                <i class="fa fa-info-circle"></i>   You need to get a short live page access token to renew the longlive token, visit <a href="https://developers.facebook.com/tools/explorer/206165426482523?method=GET&path=me%3Ffields%3Did%2Cname%2Cadmin_notes&version=v2.8" target="_blank">Facebook API Explorer Portal <i class="fa fa-external-link"></i></a>  to get a token first. You can debug your access token at <a href="https://developers.facebook.com/tools/debug/accesstoken" target="_blank">Debug Tool <i class="fa fa-external-link"></i></a>. See all the access tokens at <a href="https://developers.facebook.com/tools/accesstoken/" target="_blank">https://developers.facebook.com/tools/accesstoken/</a> .
            </div>
        }
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        <div id="msg"></div>
        <div class="form-group">
            @Html.LabelFor(model => model.Channel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Channel, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Channel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @if (Model.Channel == "Twitter")
            {
                <label class="control-label col-md-2">Consumer Key </label>
            }
            else
            {
                @Html.LabelFor(model => model.AppId, htmlAttributes: new { @class = "control-label col-md-2" })
            }
           
            <div class="col-md-10">
                @Html.EditorFor(model => model.AppId, new { htmlAttributes = new { @class = "form-control" } }) 
                @Html.ValidationMessageFor(model => model.AppId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @if (Model.Channel == "Twitter")
            {
                <label class="control-label col-md-2">Consumer Secret </label>
            }
            else
            {
                @Html.LabelFor(model => model.AppSecret, htmlAttributes: new { @class = "control-label col-md-2" })
            }
            
            <div class="col-md-10">
                @Html.EditorFor(model => model.AppSecret, new { htmlAttributes = new { @class = "form-control" } }) 
                @Html.ValidationMessageFor(model => model.AppSecret, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @if (Model.Channel == "Twitter")
            {
                <label class="control-label col-md-2">Access Token </label>
            }
            else
            {
                @Html.LabelFor(model => model.AccessToken, htmlAttributes: new { @class = "control-label col-md-2" })
            }
            
            <div class="col-md-10">
                @Html.EditorFor(model => model.AccessToken, new { htmlAttributes = new { @class = "form-control" } }) 
                @Html.ValidationMessageFor(model => model.AccessToken, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @if (Model.Channel == "Twitter")
            {
                <label class="control-label col-md-2">Token Secret </label>
            }
            else
            {
                @Html.LabelFor(model => model.LongLifeAccessToken, htmlAttributes: new { @class = "control-label col-md-2" })
            }
           
            <div class="col-md-10">
                @Html.EditorFor(model => model.LongLifeAccessToken, new { htmlAttributes = new { @class = "form-control" } }) 
                @Html.ValidationMessageFor(model => model.LongLifeAccessToken, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpiryDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExpiryDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpiryDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-primary" })  <input type="submit" value="Save" class="btn btn-info" />
                @if (Model.Channel == "Facebook")
                {
                    <input type="button" value="Renew Token" class="btn btn-success" id="btnRenew" />
                }

            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>

        $(document).ready(function () {

            $('#btnRenew').click(function (e) {

                $.ajax({
                    url: '@Url.Action("getToken", "SocialNetworks")',
                    type: "POST",

                    data: {
                        appId: $('#AppId').val(),
                        appSecret: $('#AppSecret').val(),
                        accessToken: $('#AccessToken').val()
                    },
                    success: function (result) {
                        //alert(result);
                        // here in result you will get your data
                        if (result.success) {
                            $('#LongLifeAccessToken').val(result.message);
                            $('#ExpiryDate').val(result.expiry);
                            $('#msg').html("<div class='alert alert-success'>The token has been renewed, please click on the save button to save it.</div>");
                        }
                        else {
                            $('#msg').html("<div class='alert alert-danger'>" + result.message + "</div>");
                        }


                    },
                    error: function (result) {
                        $('#msg').html("<div class='alert alert-danger'>" + result + "</div>");
                    }
                });
                e.preventDefault();
            });
        });
    </script>
}

dpaw-alerts/Views/SocialNetworks/Index.cshtml
@model IEnumerable<dpaw_alerts.Models.SocialNetwork>

@{
    ViewBag.Title = "Index";
}

<div id="breadcrumb">
    <ul class="breadcrumb">
        <li><i class="fa fa-home"></i><a href="~/Home"> Home</a></li>

        <li class="active">API Integration</li>
    </ul>
</div><!-- /breadcrumb-->
<div class="main-header clearfix">
    <div class="page-title">
        <h3 class="no-margin">Social Networks Integration</h3>

    </div><!-- /page-title -->

</div><!-- /main-header -->
<div class="row padding-md">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>   &nbsp;  @Html.ActionLink("Add New", "Create", null, new { @class = "btn btn-sm btn-info" })  &nbsp;  @Html.ActionLink("Facebook Auth", "FacebookAuth", null, new { @class = "btn btn-sm btn-success" }) &nbsp; <a href="~/glimpse.axd" class = "btn btn-sm btn-warning" target="_blank"><i class="fa fa-cog" ></i> Turn On Glimpse</a></h3>

        </div>

        <div class="panel-body">
            @if (TempData["fbmsg"] != null)
            {
                <div class="alert alert-warning">
                    @TempData["fbmsg"]
                </div>
            }

            <div id="msg"> </div>

            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Channel)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.AppId)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.AppSecret)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.ExpiryDate)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Channel)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.AppId)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.AppSecret)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ExpiryDate)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-primary" })

                            </td>
                        </tr>
                    }
                </tbody>

            </table>

        </div>
    </div>
</div>

dpaw-alerts/Views/SocialNetworks/Tweet.cshtml
@model dpaw_alerts.ViewModels.SendTweetViewModel

@{
    ViewBag.Title = "Tweet";
}

<h2>Tweet</h2>

@using (Html.BeginForm()) 
{
    <div class="alert alert-warning" >@ViewBag.Message</div>
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SendTweetViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Message, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Message, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Response, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Response, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Response, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>