dpaw-alerts/Models/Subscriber.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace dpaw_alerts.Models
{
    public class Subscriber
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; }

        [Display(Name ="First Name"), MaxLength(60), Required]
        public string FirstName { get; set; }

        [Display(Name = "Last Name"), MaxLength(60), Required]
        public string LastName { get; set; }

        [Display(Name = "Email"), MaxLength(120), Required]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string Email { get; set; }

        [Display(Name = "Mobile"), MaxLength(9)]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Mobile must be numeric without starting 0 and no blank space")]
        public string Mobile { get; set; }

        [Display(Name = "Subscription Type"), MaxLength(120, ErrorMessage = "Subscription Type is too long"), Required]
        public string SubscriptionType { get; set; }

        [Display(Name ="Subscription Date")]
        public DateTime? SubscriptionDate { get; set; }

        public string Status { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy hh:mm tt}", ApplyFormatInEditMode = true)]
        [Display(Name = "Create Date")]
        [ReadOnly(true)]
        public DateTime CreateDate
        {
            get
            {
                return (_createdOn == DateTime.MinValue) ? DateTime.Now : _createdOn;
            }
            set { _createdOn = value; }
        }
        // Private
        private DateTime _createdOn = DateTime.Now;
        [Display(Name = "Created By")]
        [ReadOnly(true)]
        public string CreatedBy { get; set; }
    }
}

dpaw-alerts/Controllers/SubscribersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using dpaw_alerts.Models;

namespace dpaw_alerts.Controllers
{
    public class SubscribersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Subscribers
        public async Task<ActionResult> Index()
        {
            return View(await db.Subscribers.ToListAsync());
        }

        // GET: Subscribers/Details/5
        public async Task<ActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subscriber subscriber = await db.Subscribers.FindAsync(id);
            if (subscriber == null)
            {
                return HttpNotFound();
            }
            return View(subscriber);
        }

        // GET: Subscribers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Subscribers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,FirstName,LastName,Email,Mobile,SubscriptionDate,SubscriptionType,Status,CreateDate,CreatedBy")] Subscriber subscriber)
        {
            if(!ValidateSubscriber(subscriber.Email))
            {
                string usr = User.Identity.Name;
           
            if (ModelState.IsValid)
            {
                subscriber.Id = Guid.NewGuid();
                subscriber.CreatedBy = usr;
                db.Subscribers.Add(subscriber);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            
            }

            ModelState.AddModelError("", "The email address exists in the system, you cannot use same email.");

            return View(subscriber);
        }

        // GET: Subscribers/Edit/5
        public async Task<ActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subscriber subscriber = await db.Subscribers.FindAsync(id);
            if (subscriber == null)
            {
                return HttpNotFound();
            }
            return View(subscriber);
        }

        // POST: Subscribers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,FirstName,LastName,Email,Mobile,SubscriptionDate,Status,CreateDate,CreatedBy, SubscriptionType")] Subscriber subscriber)
        {
            if (ModelState.IsValid)
            {
                db.Entry(subscriber).State = EntityState.Modified;
                //exclude columns from modification
                db.Entry(subscriber).Property(x => x.CreateDate).IsModified = false;
                db.Entry(subscriber).Property(x => x.CreatedBy).IsModified = false;
                //save changes to the database
                await db.SaveChangesAsync();
                TempData["Message"] = String.Format("Subscriber <span class='red'> {0} {1} </span> has been updated successfully!", subscriber.FirstName, subscriber.LastName);
                return RedirectToAction("Index");
            }
            return View(subscriber);
        }

        protected bool ValidateSubscriber(string email)
        {
            
            var subs = db.Subscribers.Where(a => a.Email == email.ToLower()).Count();
            if (subs > 0)
            {
                return true;
            }
            return false;

        }

        [HttpPost]
        //  [ChildActionOnly]
        public async Task<ActionResult> AjaxDelete(Guid? Id)
        {

            if (Id == null)
            {
                return Json(new { success = false });
            }

            Subscriber subscriber = await db.Subscribers.FindAsync(Id);
            db.Subscribers.Remove(subscriber);
            await db.SaveChangesAsync();
            return Json(new { success = true });


        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

dpaw-alerts/Views/Subscribers/Create.cshtml
@model dpaw_alerts.Models.Subscriber

@{
    ViewBag.Title = "Create";
}

<div id="breadcrumb">
    <ul class="breadcrumb">
        <li><i class="fa fa-home"></i><a href="~/Home"> Home</a></li>
        <li><a href="~/Subsribers">Subscribers</a></li>
        <li class="active">New subscriber</li>
    </ul>
</div><!-- /breadcrumb-->
<div class="main-header clearfix">
    <div class="page-title">
        <h3 class="no-margin">New Subscriber</h3>
        <p>You can create a new subscriber in this section.</p>
    </div><!-- /page-title -->

</div><!-- /main-header -->


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="row padding-md">
        <div class="col-md-6">

            <div class="form-horizontal">
              
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Mobile, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "form-control", @maxlength = "9" } })
                        @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.SubscriptionType, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-6">
                        @Html.DropDownListFor(model => model.SubscriptionType, new SelectList(
                  new List<Object>{
                      new { value = "" , text = "Select one"  },
                       new { value = "Email" , text = "Email"  },
                       new { value = "SMS" , text = "SMS" },
                       new { value="Email and SMS", text ="Email-SMS"},
                       new { value="None", text ="None"}

                    },
                  "value",
                  "text"
                 ), new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.SubscriptionType, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.SubscriptionDate, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.SubscriptionDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SubscriptionDate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-6">
                        
                        @Html.DropDownListFor(model => model.Status, new SelectList(
                  new List<Object>{
                       new { value = "Active" , text = "Active"  },
                       new { value = "Inactive" , text = "Inactive" }

                    },
                  "value",
                  "text"
                   ), new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                       @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-primary" }) <input type="submit" value="Create" class="btn btn-info" />
                    </div>
                </div>
            </div>

        </div>
    </div>
}



@section Scripts {
@Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/bundles/date")
@Styles.Render("~/Content/css/form")

    <script>
        $(function () {

            //fix jquery date validation issue
            $.validator.methods.date = function (value, element) {
                return this.optional(element) || $.datetimepicker.parsedate('dd/mm/yy', value);
            }

            $.datetimepicker.setDateFormatter({
                parseDate: function (date, format) {
                    var d = moment(date, format);
                    return d.isValid() ? d.toDate() : false;
                },

                formatDate: function (date, format) {
                    return moment(date).format(format);
                }
            });

            $('#SubscriptionDate').datetimepicker({
                format: 'DD/MM/YYYY',
                timepicker: false,
                formatDate: 'DD/MM/YYYY',
                minDate: '-1970/01/02'
            });
        });
    </script>
}

dpaw-alerts/Views/Subscribers/Edit.cshtml
@model dpaw_alerts.Models.Subscriber

@{
    ViewBag.Title = "Edit";
}

<div id="breadcrumb">
    <ul class="breadcrumb">
        <li><i class="fa fa-home"></i><a href="~/Home"> Home</a></li>
        <li><a href="~/Subsribers">Subscribers</a></li>
        <li class="active">Edit subscriber</li>
    </ul>
</div><!-- /breadcrumb-->
<div class="main-header clearfix">
    <div class="page-title">
        <h3 class="no-margin">Edit Subscriber</h3>

    </div><!-- /page-title -->

</div><!-- /main-header -->


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="row padding-md">
        <div class="col-md-6">

            <div class="form-horizontal">
               
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Mobile, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "form-control", @maxlength = "9" } })
                        @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.SubscriptionType, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-6">
                        @Html.DropDownListFor(model => model.SubscriptionType, new SelectList(
                  new List<Object>{
                       new { value = "Email" , text = "Email"  },
                       new { value = "SMS" , text = "SMS" },
                       new { value="Email-SMS", text ="Email and SMS"},
                       new { value="None", text="None"}

                    },
                  "value",
                  "text",
                 Model.SubscriptionType), new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.SubscriptionType, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.SubscriptionDate, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.SubscriptionDate, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.SubscriptionDate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-6">
                        @Html.DropDownListFor(model => model.Status, new SelectList(
                  new List<Object>{
                       new { value = "Active" , text = "Active"  },
                       new { value = "Inactive" , text = "Inactive" }

                    },
                  "value",
                  "text",
                 Model.Status), new { @class = "form-control" })

                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-6">
                      @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-primary" })  <input type="submit" value="Save" class="btn btn-info" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}


@section Scripts {
@Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/bundles/date")
@Styles.Render("~/Content/css/form")

<script>
        $(function () {

            //fix jquery date validation issue
            $.validator.methods.date = function (value, element) {
                return this.optional(element) || $.datetimepicker.parsedate('dd/mm/yy', value);
            }

            $.datetimepicker.setDateFormatter({
                parseDate: function (date, format) {
                    var d = moment(date, format);
                    return d.isValid() ? d.toDate() : false;
                },

                formatDate: function (date, format) {
                    return moment(date).format(format);
                }
            });

            //$('#SubscriptionDate').datetimepicker({
            //    format: 'DD/MM/YYYY',
            //    timepicker: false,
            //    formatDate: 'DD/MM/YYYY',
            //    minDate: '-1970/01/02'
            //});
        });
</script>
}

dpaw-alerts/Views/Subscribers/Index.cshtml
@model IEnumerable<dpaw_alerts.Models.Subscriber>

@{
    ViewBag.Title = "Index";
}

<div id="breadcrumb">
    <ul class="breadcrumb">
        <li><i class="fa fa-home"></i><a href="~/Home"> Home</a></li>

        <li class="active">Subscribers</li>
    </ul>
</div><!-- /breadcrumb-->
<div class="main-header clearfix">
    <div class="page-title">
        <h3 class="no-margin">Newsletter Subscribers</h3>

    </div><!-- /page-title -->

</div><!-- /main-header -->

<p>
    
</p>

<div class="row padding-md">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>
                @Html.ActionLink("Add New", "Create", null, new { @class = "btn btn-info" })
                @Html.ActionLink("Email Template",  "Index", "EmailTemplates", null,  new { @class = "btn btn-primary" })
            </h3>

        </div>

        <div class="panel-body">
            @if (TempData["Message"] != null)
            {
                <div class="alert alert-success" id="msg">
                    <i class="glyphicon glyphicon-info-sign"></i> @Html.Raw(TempData["Message"].ToString())
                </div>
            }
           <div id="msg"> </div>
@if (Model.Count() == 0)
{
    <div class="alert alert-warning">No subscriber has been created yet.</div>
}
else
{
            <table class="table table-striped table-hover" id="dataTable">
                <thead>
                    <tr>
                        <th>##</th>
                        <th>
                            @Html.DisplayNameFor(model => model.FirstName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.LastName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Email)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Mobile)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.SubscriptionDate)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.SubscriptionType)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Status)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.CreateDate)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.CreatedBy)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @{int rowNo = 0;}
                    @foreach (var item in Model)
                    {
                        <tr>
                            
                            <td> @(rowNo += 1)</td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FirstName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.LastName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Email)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Mobile)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.SubscriptionDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.SubscriptionType)
                            </td>
                            <td>
                                @if (item.Status == "Active")
                                {
                                    <i class="fa fa-circle green" title="Active"></i>
                                }
                                else
                                {
                                    <i class="fa fa-circle red" title="Inactive"></i>
                                }
                                
                                
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CreateDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CreatedBy)
                            </td>
                            <td>
                                <div class="btn-group-xs">
                                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-info" })

                                    <input type="button" value="Delete" class="btn btn-danger delete" data-value="@item.Id" />
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
}
            </div>
        </div>
    </div>


<script>

    $(function () {

        $(".delete").click(function (e) {

            if (confirm('Are you sure want to delete?')) {
                e.preventDefault();
                var parent = $(this).parent().parent().parent();

                {

                    $.ajax({
                        url: '@Url.Action("AjaxDelete", "Subscribers")',
                        type: 'POST',
                        dataType: 'json',
                        async: true,
                        data: { 'id': $(this).attr('data-value') },
                        contentType: 'application/x-www-form-urlencoded',
                        beforeSend: function () {
                            parent.animate({ 'backgroundColor': '#fb6c6c' }, 300);
                        },
                        success: function (data) {
                            if (data.success) {

                                $("#msg").html("<div class='alert alert-success'>The subsriber has been deleted from the system! </div>");

                                parent.slideUp(300, function () {
                                    parent.remove();
                                });

                            }
                            else {
                                // show a message in a alert or div
                                $("#msg").html("<div class='alert alert-danger'>Sorry, the subscriber cannot be deleted! </div>");
                            }
                        }
                    });
                }
            }
            else return false;
        });
    

        //set the data table
        $('#dataTable').dataTable({
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "aoColumnDefs": [{ "bSortable": false, "aTargets": [10] }]
        });
    });


</script>